<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "eventnews"
 *
 * Auto generated by Extension Builder 2015-02-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'news events',
	'description' => 'Events for news',
	'category' => 'plugin',
	'author' => 'Georg Ringer',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'news' => '3.0.0',
		),
		'conflicts' => array(),
		'suggests' => array(),
	),
);